let Cards={
    0:{
        'name':'General',
        'life':5,
        'attack':3,
        'cost':4,
        'url':require('../src/assets/general.jpg')
    },
    1:{
        'name':'Assasin',
        'life':0,
        'attack':6,
        'cost':2,
        'url':require('../src/assets/assasin.jpg')
    },
    2:{
        'name':'Barricade',
        'life':5,
        'attack':1,
        'cost':2,
        'url':require('../src/assets/baricade.jpg')
    },
    3:{
        'name':'jolly joker',
        'life':3,
        'attack':3,
        'cost':1,
        'url':require('../src/assets/jollyjoker.jpg')
    },
    4:{
        'name':'harci szekerce',
        'life':0,
        'attack':5,
        'cost':3,
        'url':require('../src/assets/szekerce.jpg')
    },
    5:{
        'name':'Gyalogság',
        'life':2,
        'attack':1,
        'cost':1,
        'url':require('../src/assets/infantry.jpg')
    },
    6:{
        'name':'Tüzérség',
        'life':1,
        'attack':3,
        'cost':2,
        'url':require('../src/assets/artillery.jpg')
    },
    7:{
        'name':'Titkos terv',
        'life':0,
        'attack':2,
        'cost':1,
        'url':require('../src/assets/topsecret.jpg')
    },
    8:{
        'name':'Árulás',
        'life':-1,
        'attack':3,
        'cost':1,
        'url':require('../src/assets/betray.jpg')
    },
    9:{
        'name':'Rakéta állomás',
        'life':1,
        'attack':7,
        'cost':4,
        'url':require('../src/assets/missle.jpg')
    },
    10:{
        'name':'Tank',
        'life':3,
        'attack':3,
        'cost':3,
        'url':require('../src/assets/tank.jpg')
    }
}
exports.Cards=Cards